export const DEMO_ANALYSIS = {
  id: "734fdd98-8bde-41e9-9bd2-2f42d9a349fb",
  competitor_id: "demo-1",
  created_at: "2026-01-20T09:17:51.846Z",
  analysis_status: "completed",
  content_analysis: {
    source: "rss",
    status: "success",
    analyzed_at: "2026-01-20T09:17:48.168Z",
    content_types: {
      ai: 1,
      git: 1,
      llm: 1,
      node: 1,
      rust: 1,
      funny: 1,
      jokes: 2,
      react: 2,
      github: 1,
      webdev: 5,
      discuss: 4,
      frontend: 1,
      security: 1,
      beginners: 2,
      javascript: 5,
      programming: 4,
      productivity: 1,
    },
    average_length: {
      length_category: "long",
      estimated_word_count: 805,
      average_summary_length: 4028,
    },
    recent_articles: [
      {
        url: "https://dev.to/tech-insights/your-github-contribution-graph-means-absolutely-nothing-and-heres-why-2kjc",
        title:
          "Your GitHub Contribution Graph Means Absolutely Nothing - And Here’s Why",
        summary:
          "If your GitHub contribution graph disappeared tomorrow, would that make you a worse developer?...",
        categories: ["github", "discuss", "programming"],
        published_at: "2026-01-13T11:42:28.000+00:00",
      },
      {
        url: "https://dev.to/sylwia-lask/when-react-starts-acting-like-jquery-and-you-can-totally-tell--3kpe",
        title:
          "When React Starts Acting Like jQuery (and You Can Totally Tell 😅)",
        summary:
          "I’m not a fangirl of any single framework. For me, frameworks are tools...",
        categories: ["react", "webdev", "javascript", "beginners"],
        published_at: "2026-01-08T13:00:12.000+00:00",
      },
      {
        url: "https://dev.to/sylwia-lask/yes-true-true-2-and-no-javascript-isnt-broken-37p7",
        title: "Yes, true + true === 2. And No, JavaScript Isn’t Broken",
        summary:
          "JavaScript has been my main work language for years now (and of course these days it’s mostly TypeScript 😉)...",
        categories: ["javascript", "node", "webdev", "beginners"],
        published_at: "2026-01-04T12:19:52.000+00:00",
      },
      {
        url: "https://dev.to/sylwia-lask/why-do-you-code-a-surprisingly-hard-question-4ak4",
        title: "“Why Do You Code?” - A Surprisingly Hard Question",
        summary:
          "The end of the year is coming, and for me it’s always a time of reflection...",
        categories: ["programming", "discuss"],
        published_at: "2025-12-30T13:03:01.000+00:00",
      },
      {
        url: "https://dev.to/sylwia-lask/7-lies-developers-keep-telling-themselves-and-somehow-still-believe-46nh",
        title:
          "7 Lies Developers Keep Telling Themselves (And Somehow Still Believe)",
        summary:
          "The holidays are coming 🎄 And between making pierogi 🥟 and baking gingerbread cookies...",
        categories: ["jokes", "discuss"],
        published_at: "2025-12-22T12:12:44.000+00:00",
      },
    ],
    new_articles_count: 10,
    publishing_frequency: {
      date_range: {
        to: "2026-01-13",
        from: "2025-11-13",
      },
      frequency_rating: "moderate",
      articles_per_month: 5.9,
      total_articles_analyzed: 12,
    },
  },
  seo_analysis: {
    domain: "dev.to",
    backlinks: 179979,
    analyzed_at: "2026-01-20T09:17:49.651Z",
    data_source: "DataForSEO",
    domain_rank: 2488,
    root_domain: "dev.to",
    top_keywords: [
      {
        cpc: 4.62,
        etv: 27.36,
        keyword: "javascript tutorials",
        position: 1,
        search_volume: 90,
      },
      {
        cpc: 2.23,
        etv: 21.28,
        keyword: "web development trends",
        position: 2,
        search_volume: 70,
      },
    ],
    organic_traffic: 2167362,
    original_domain: "dev.to",
    domain_authority: 82,
    organic_keywords: 1011783,
    referring_domains: 11537,
  },
  topics_identified: {
    topics: [
      { name: "javascript webdev", count: 4 },
      { name: "discuss programming", count: 3 },
      { name: "webdev", count: 5 },
      { name: "javascript", count: 5 },
      { name: "beginners javascript", count: 2 },
    ],
    total_unique_topics: 77,
  },
  keywords_found: {
    keywords: [
      { word: "commit messages", frequency: 10 },
      { word: "clean code", frequency: 9 },
      { word: "contribution graph", frequency: 8 },
      { word: "true true", frequency: 7 },
      { word: "github contribution", frequency: 5 },
    ],
    total_keywords: 3400,
  },
  new_articles_found: 10,
  content_quality_score: 99.5,
  ai_visibility_score: 92.5,
  seo_score: 91.0,
  llm_share_of_voice: 20.0,
  overall_score: 95.25,
  recommendations: [
    {
      type: "publishing_frequency",
      details: {
        your_frequency: 25.0,
        competitor_frequency: 5.9,
      },
      message:
        "Competitor publishes 5.9 articles/month. Consider increasing your publishing frequency.",
      priority: "high",
    },
    {
      type: "content_gaps",
      action:
        "Review content gap analysis and plan articles for high-priority topics",
      details: [
        {
          topic: "javascript webdev",
          example_article: null,
          suggested_titles: [
            "The Ultimate Guide to Javascript Webdev",
            "How to Master Javascript Webdev in 2026",
          ],
        },
        {
          topic: "javascript webdev",
          example_article: null,
          suggested_titles: [
            "The Ultimate Guide to Javascript Webdev",
            "How to Master Javascript Webdev in 2026",
          ],
        },
        {
          topic: "javascript webdev",
          example_article: null,
          suggested_titles: [
            "The Ultimate Guide to Javascript Webdev",
            "How to Master Javascript Webdev in 2026",
          ],
        },
        {
          topic: "javascript webdev",
          example_article: null,
          suggested_titles: [
            "The Ultimate Guide to Javascript Webdev",
            "How to Master Javascript Webdev in 2026",
          ],
        },
      ],
      message: "Found 10 topics your competitor covers that you don't.",
      priority: "medium",
    },
  ],
};

export const DEMO_COMPETITORS = [
  {
    id: "demo-1",
    name: "Suraj Vishwakarma",
    website_url: "https://dev.to/surajondev",
    domain: "dev.to",
    description: "Frontend Developer & Technical Writer",
    active: true,
    needs_analysis: false,
    articles_tracked: 12,
    last_analyzed_at: "2026-01-20T09:17:51.846Z",
    created_at: "2026-01-20T09:17:51.846Z",
    updated_at: "2026-01-20T09:17:51.846Z",
    metrics: {
      organic_keywords: 1011783,
      organic_traffic: 2167362,
      domain_authority: 82,
      backlinks: 179979,
    },
  },
];

export const DEMO_KEYWORDS = [
  {
    keyword: "nextjs 14 tutorial",
    search_volume: 12500,
    difficulty: 65,
    cpc: 3.5,
    opportunity_score: 85,
    source: "semantic_similarity",
    relevance_score: 0.98,
    competitor_using: true,
    intent: "informational",
    trend: "+25%",
    ai_visibility_score: 8.5,
  },
  {
    keyword: "react server components",
    search_volume: 8900,
    difficulty: 58,
    cpc: 2.8,
    opportunity_score: 92,
    source: "ai_prediction",
    relevance_score: 0.95,
    competitor_using: false,
    intent: "informational",
    trend: "+120%",
    ai_visibility_score: 7.2,
  },
  {
    keyword: "typescript best practices",
    search_volume: 5200,
    difficulty: 45,
    cpc: 4.2,
    opportunity_score: 88,
    source: "google_autocomplete",
    relevance_score: 0.9,
    competitor_using: true,
    intent: "informational",
    trend: "+15%",
    ai_visibility_score: 9.1,
  },
  {
    keyword: "tailwind css vs bootstrap",
    search_volume: 15600,
    difficulty: 42,
    cpc: 1.5,
    opportunity_score: 75,
    source: "competitor",
    relevance_score: 0.85,
    competitor_using: true,
    intent: "commercial",
    trend: "+8%",
    ai_visibility_score: 6.8,
  },
  {
    keyword: "shadcn ui components",
    search_volume: 6700,
    difficulty: 35,
    cpc: 0.8,
    opportunity_score: 95,
    source: "blog_content",
    relevance_score: 0.99,
    competitor_using: false,
    intent: "informational",
    trend: "+200%",
    ai_visibility_score: 9.5,
  },
  {
    keyword: "server actions nextjs",
    search_volume: 4500,
    difficulty: 52,
    cpc: 2.1,
    opportunity_score: 82,
    source: "semantic_similarity",
    relevance_score: 0.94,
    competitor_using: false,
    intent: "informational",
    trend: "+85%",
    ai_visibility_score: 8.0,
  },
  {
    keyword: "zustand vs redux",
    search_volume: 3200,
    difficulty: 38,
    cpc: 1.2,
    opportunity_score: 90,
    source: "ai_prediction",
    relevance_score: 0.92,
    competitor_using: true,
    intent: "informational",
    trend: "+45%",
    ai_visibility_score: 7.5,
  },
  {
    keyword: "web accessibility guide",
    search_volume: 9800,
    difficulty: 60,
    cpc: 5.5,
    opportunity_score: 72,
    source: "google_autocomplete",
    relevance_score: 0.88,
    competitor_using: true,
    intent: "informational",
    trend: "+10%",
    ai_visibility_score: 8.9,
  },
  {
    keyword: "css grid vs flexbox",
    search_volume: 22000,
    difficulty: 30,
    cpc: 0.9,
    opportunity_score: 65,
    source: "competitor",
    relevance_score: 0.8,
    competitor_using: true,
    intent: "informational",
    trend: "-5%",
    ai_visibility_score: 6.2,
  },
  {
    keyword: "full stack project ideas",
    search_volume: 18500,
    difficulty: 55,
    cpc: 1.8,
    opportunity_score: 78,
    source: "blog_content",
    relevance_score: 0.85,
    competitor_using: false,
    intent: "informational",
    trend: "+12%",
    ai_visibility_score: 7.8,
  },
  {
    keyword: "docker for frontend developers",
    search_volume: 4100,
    difficulty: 48,
    cpc: 2.5,
    opportunity_score: 84,
    source: "semantic_similarity",
    relevance_score: 0.91,
    competitor_using: false,
    intent: "informational",
    trend: "+18%",
    ai_visibility_score: 8.3,
  },
  {
    keyword: "react performance optimization",
    search_volume: 7600,
    difficulty: 62,
    cpc: 3.8,
    opportunity_score: 80,
    source: "ai_prediction",
    relevance_score: 0.93,
    competitor_using: true,
    intent: "informational",
    trend: "+22%",
    ai_visibility_score: 9.0,
  },
  {
    keyword: "nodejs architecture patterns",
    search_volume: 3800,
    difficulty: 50,
    cpc: 4.1,
    opportunity_score: 86,
    source: "google_autocomplete",
    relevance_score: 0.89,
    competitor_using: true,
    intent: "informational",
    trend: "+7%",
    ai_visibility_score: 8.7,
  },
  {
    keyword: "graphql vs rest api",
    search_volume: 11200,
    difficulty: 54,
    cpc: 2.9,
    opportunity_score: 76,
    source: "competitor",
    relevance_score: 0.87,
    competitor_using: true,
    intent: "commercial",
    trend: "+3%",
    ai_visibility_score: 7.1,
  },
  {
    keyword: "web assembly introduction",
    search_volume: 2900,
    difficulty: 68,
    cpc: 1.4,
    opportunity_score: 81,
    source: "blog_content",
    relevance_score: 0.84,
    competitor_using: false,
    intent: "informational",
    trend: "+35%",
    ai_visibility_score: 9.2,
  },
  {
    keyword: "microservices vs monolith",
    search_volume: 8400,
    difficulty: 56,
    cpc: 3.2,
    opportunity_score: 74,
    source: "semantic_similarity",
    relevance_score: 0.82,
    competitor_using: true,
    intent: "informational",
    trend: "+5%",
    ai_visibility_score: 6.5,
  },
  {
    keyword: "progressive web apps example",
    search_volume: 5600,
    difficulty: 45,
    cpc: 1.9,
    opportunity_score: 79,
    source: "ai_prediction",
    relevance_score: 0.86,
    competitor_using: false,
    intent: "informational",
    trend: "+9%",
    ai_visibility_score: 7.6,
  },
  {
    keyword: "css animations tutorial",
    search_volume: 13800,
    difficulty: 40,
    cpc: 1.1,
    opportunity_score: 70,
    source: "google_autocomplete",
    relevance_score: 0.83,
    competitor_using: true,
    intent: "informational",
    trend: "+14%",
    ai_visibility_score: 6.9,
  },
  {
    keyword: "frontend developer roadmap 2026",
    search_volume: 25000,
    difficulty: 75,
    cpc: 0.5,
    opportunity_score: 60,
    source: "competitor",
    relevance_score: 0.96,
    competitor_using: true,
    intent: "informational",
    trend: "+40%",
    ai_visibility_score: 9.8,
  },
  {
    keyword: "javascript design patterns",
    search_volume: 9200,
    difficulty: 58,
    cpc: 2.6,
    opportunity_score: 83,
    source: "blog_content",
    relevance_score: 0.94,
    competitor_using: true,
    intent: "informational",
    trend: "+6%",
    ai_visibility_score: 8.4,
  },
  {
    keyword: "react hooks explained",
    search_volume: 16500,
    difficulty: 35,
    cpc: 1.3,
    opportunity_score: 77,
    source: "semantic_similarity",
    relevance_score: 0.97,
    competitor_using: true,
    intent: "informational",
    trend: "+11%",
    ai_visibility_score: 8.1,
  },
];
